export const GlobalStyles = {
    colors: {
        black: '#000000',
        white: '#ffffff',
        grey1: '#8e8e93',
        grey2: '#aeaeb2',
        grey3: '#c7c7cc',
        grey4: '#d1d1d6',
        grey5: '#e5e5ea',
        grey6: '#f2f2f7',
        primaryGreen: '#54b175',
        primaryOrange: '#fe6e4c',
        primaryYellow: '#febf43',
        primaryPurple: '#9b81e5',
        primaryTosca: '#03b0a9',
        secondaryGreen: '#e4f3ea',
        secondaryOrange: '#ffece8',
        secondaryYellow: '#fff6e4',
        secondaryPurple: '#f1edfc',
        secondaryTosca: '#ddf5f4',
        bgPrimary: '#ffffff',
        bgSecondary: '#fbfbfb',
        groupedBgPrimary: '#ffffff',
        groupedBgSecondary: '#f2f2f7',
        separatorOpaque: '#c6c6c8',
        separatorNotOpaque: '#b9b9bb',
        fillsPrimary: '#e4e4e6',
        fillsSecondary: '#e9e9eb',
        fillsTertiary: '#efeff0',
        fillsQuarternary: '#f4f4f5',
        labelsPrimary: '#22292e',
        labelsSecondary: '#8a8a8e',
        labelsTertiary: '#c5c5c7',
        labelsQuarternary: '#f8f8f8',
        disable: '#979592'
    },
};
